### ISSUE TITLE
Decode Extrinsic

### ISSUE THREAD

**Issue by crossle** [itering/substrate-api-rpc#1]
1. When decode extrinsic, must fill metadataInstant ?
2. How to get the transaction fee only use RPC via http?

**Comment by freehere107** [comment]
> 1. When decode extrinsic, must fill metadataInstant ?
> 2. How to get the transaction fee only use RPC via http?

1. Must fill metadataInstant, metadata info like ethereum contract Abi
2. You can find there https://github.com/itering/substrate-api-rpc/blob/3f2460e132a7350ca7cac10fcd165c0d5e504053/rpc/system.go#L97.

**Comment by crossle** [comment]
Thanks, BTW, How to get the extrinsic status? success or failure?

**Comment by freehere107** [comment]
@crossle https://github.com/itering/subscan-essentials/blob/ad1c7ccfa54c1bf34342ed007d47aad9101b5af1/internal/service/extrinsic.go#L110

**Comment by crossle** [comment]
```
	decodeEvent, err := substrate.DecodeEvent(event, metaInstant, specVersion)
	if err != nil {
		return nil, err
	}
```
When decode event like block 2088622, error:

`Recovering from panic in DecodeEvent error is: runtime error: index out of range [5] with length 3`

**Comment by crossle** [comment]
Sometime error `Recovering from panic in DecodeEvent error is: Vec length 672001531 exceeds 1000`

**Comment by freehere107** [comment]
@crossle Your need to check using event relate metadata and custom type

**Comment by crossle** [comment]
How to use event metadata, i get the metadata from rpc `state_getMetadata`

**Comment by freehere107** [comment]
@crossle state_getMetadata，you need use event block relate metadata 
``
curl -X POST -H "Content-Type: application/json"  --data '{"id":6,"jsonrpc":"2.0","method":"state_getMetadata","params":[blockHash]}'
``

**Comment by crossle** [comment]
> @crossle state_getMetadata，you need use event block relate metadata
> `curl -X POST -H "Content-Type: application/json" --data '{"id":6,"jsonrpc":"2.0","method":"state_getMetadata","params":[blockHash]}'`

Thanks, I loss the blockHash param...

**Comment by crossle** [comment]
> Sometime error `Recovering from panic in DecodeEvent error is: Vec length 672001531 exceeds 1000`

@freehere107 spec version must match the metadata?

**Comment by freehere107** [comment]
> > Sometime error `Recovering from panic in DecodeEvent error is: Vec length 672001531 exceeds 1000`
> 
> @freehere107 spec version must match the metadata?

@crossle  Right!

**Comment by crossle** [comment]
> @crossle Your need to check using event relate metadata and custom type

Can you commit the polkadot custom type to the project? like decode event, or where i can find the custom type?

**Comment by freehere107** [comment]
@crossle you may reference https://github.com/itering/scale.go/tree/master/network

**Comment by crossle** [comment]
> @crossle you may reference https://github.com/itering/scale.go/tree/master/network
Why not make the json to go file? others can import it

**Comment by freehere107** [comment]
@crossle In fact, this custom JSON can only be used for testing. The custom JSON used by subscan is not open source.

**Comment by crossle** [comment]
> @crossle In fact, this custom JSON can only be used for testing. The custom JSON used by subscan.io is not open source.

Any different?

**Comment by freehere107** [comment]
@crossle https://github.com/itering/scale.go/tree/master/network  Updates are not frequent

**Comment by crossle** [comment]
> Updates are not frequent

How about make the json to *.go file?
