### ISSUE TITLE
websocket Init() function params not in effect

### ISSUE THREAD

**Issue by CryptoDavChen** [itering/substrate-api-rpc#12]
`			SubscribeConn.Dial(wsEndPoint, nil)
			for _, o := range options {
				o.Apply(SubscribeConn)
			}
`

maybe need change to:

`
			for _, o := range options {
				o.Apply(SubscribeConn)
			}
			SubscribeConn.Dial(wsEndPoint, nil)
`

**Comment by CryptoDavChen** [comment]
```
			SubscribeConn.Dial(wsEndPoint, nil)
			for _, o := range options {
				o.Apply(SubscribeConn)
			}
```
maybe need change to:
```
			for _, o := range options {
				o.Apply(SubscribeConn)
			}
			SubscribeConn.Dial(wsEndPoint, nil)
```

**Comment by freehere107** [comment]
@CryptoDavChen OK，thank you feedback
