### ISSUE TITLE
 8284618-3 get payment_queryInfo err: websocket: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by CryptoDavChen** [itering/substrate-api-rpc#13]
8284618-3's extrinsic raw is very big, about 1.2MB, when payment_queryInfo, get this error :
 
 websocket: close 1006 (abnormal closure): unexpected EOF
 
 I tried edit setDefaultDialer() add WriteBufferSize, then work well. Maybe need add a SetWriteBufferSize func. please have a check, thanks.
 
 ```
 	rc.dialer = &websocket.Dialer{
		HandshakeTimeout: handshakeTimeout,
		Proxy:            rc.Proxy,
		TLSClientConfig:  &tls.Config{RootCAs: nil, InsecureSkipVerify: true},
		WriteBufferSize:  5242880,
	}
 ```

**Comment by freehere107** [comment]
@CryptoDavChen Thank you feedback, this is an undiscovered bug

**Comment by freehere107** [comment]
Options have been added,   https://github.com/itering/substrate-api-rpc/commit/a5d1bd054950582cae587f1d1f5c5cd81dba7717, thank you feedback
