### ISSUE TITLE
not able to get the storage with ReadStorage method 

### ISSUE THREAD

**Issue by andropixels** [itering/substrate-api-rpc#16]
Can someone please help me to understand how to make a call to the extrinsics which requires arguments to passed in 
i observed we can get a data from the extrinsics which do not requires arguments but with extrinsics with arguments it is giving me null string 
as in this example i am trying to call the erasRewardPoints extrinsic from staking module , i am passing the args array 
still it will give me the null string . 
thanks in advance 

![image](https://user-images.githubusercontent.com/69791440/186191515-2853687e-4b41-4ab5-add0-7b0334fab5c5.png)

**Comment by freehere107** [comment]
@andropixels Hi, args need to encode, you can try this https://github.com/itering/scale.go/blob/master/types/types_test.go#L300

**Comment by andropixels** [comment]
thanks !
