### ISSUE TITLE
Decode events of Westend error, height: 13128237

### ISSUE THREAD

**Issue by CryptoDavChen** [itering/substrate-api-rpc#26]
Hi team, 13128237 is first block of 9310 in Westend, and i tried use 9300 and 9310 metadata to parse events, both return this error:
`Recovering from panic in DecodeEvent error is: Not find Event Lookup c83f, please check metadata info.`

Please have a look, thanks.

**Comment by freehere107** [comment]
This is a problem caused by runtime upgrade, https://westend.subscan.io/block/13128237?tab=event, the upgraded block should use the metadata of the previous block
