### ISSUE TITLE
Need some support for get extrinsic status

### ISSUE THREAD

**Issue by CryptoDavChen** [itering/substrate-api-rpc#28]
Hi team, i need some support for get extrinsic status:

1.How to get extrinsic's fail reason via RPC, like this one:
Result: Failed（NotProxy）
https://westend.subscan.io/extrinsic/12967794-2

I know maybe need use index and error in System-ExtrinsicFailed params.

2. Another question is , like this extrinsic, event is System-ExtrinsicSuccess, but Result is:
 Failed（InsufficientBond）, so what is the status judgement criteria ?

https://polkadot.subscan.io/extrinsic/12556856-2

**Comment by freehere107** [comment]
First, you need to judge whether the event is ``System-ExtrinsicFail. ``
If it fails, it is directly judged that the transaction failed

If the event is ``System-ExtrinsicSuccess. ``
Additional judgment is required, the execution result of ``proxy (ProxyExecuted). ``
