### ISSUE TITLE
how get account's role

### ISSUE THREAD

**Issue by CryptoDavChen** [itering/substrate-api-rpc#5]
Hi Team, how get account's role, like Nominator, and how get account staked validators by this api, please give a help, thaks a lot! @freehere107

**Comment by freehere107** [comment]
@CryptoDavChen You can use this https://docs.api.subscan.io/#search-account

**Comment by CryptoDavChen** [comment]
Thanks @freehere107 , i think i need get these data by myself, subsan's data has limit rate

**Comment by alexqrid** [comment]
@freehere107 Are you getting this data executing several queries in your database or there is an opportunity to get this info from the node's API?

**Comment by freehere107** [comment]
@alexqrid subscan stores all of these in the database
